/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Safely access environment variables with fallbacks
const getEnvVar = (key: string, fallback: string): string => {
  try {
    // Check if we're in a Vite environment with import.meta.env
    if (typeof window !== 'undefined' && import.meta && import.meta.env) {
      return import.meta.env[key] || fallback;
    }
    return fallback;
  } catch {
    return fallback;
  }
};

// For local development, these can be overridden with environment variables
export const projectId = getEnvVar('VITE_SUPABASE_PROJECT_ID', "zwbcykxbhzdlguitovdy");
export const publicAnonKey = getEnvVar('VITE_SUPABASE_ANON_KEY', "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3YmN5a3hiaHpkbGd1aXRvdmR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzAwMDgsImV4cCI6MjA3MzcwNjAwOH0.gGjdnrAuKKSE74Hv_kmHRoHb5KHqtr2Mi-msqdX4nn0");
export const supabaseUrl = getEnvVar('VITE_SUPABASE_URL', `https://${projectId}.supabase.co`);